# Site settings
title: RecalBlog
header-img: img/recalbox-cover.jpg
email: mika@recalbox.com
copyright_name: Recalbox
description: "Blog about recalbox os and retrogamming lovers !"
#baseurl: "/recalbox-os"
url: "http://yourdomain.com"
twitter_username: Recalbox
github_username: Recalbox 
facebook_username:  Recalbox
email_username:  mika@recalbox.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-multiple-languages-plugin]
languages: ["en","fr"]
exclude_from_localizations: ["javascript", "images", "css"]
